### ISSUE TITLE
Storage Size Limitations Android/IOS

### ISSUE THREAD

**Issue by ahmad6242** [globules-io/MongOGX#5]
Hello,
Nice work there. 
I just want to know what is the Limit for the Storage of data in Android/IOS.
I think it might be 5Mb, so in that case is that possible to increase that memory limit?
Please help me with that. 
Thanks... 👍

**Comment by globules-io** [comment]
Hello. Thank you! If you use the local storage, yes you will be limited to 5Mb (it might even be 2mb in webview depending on the version) and you cannot increase it.
If you need more space, you can give a shot at using the other storage mode, OGX.Mongogx.APP_STORAGE.

**Comment by ahmad6242** [comment]
OKeyyyy... I will give it a try... Thanks 💯

**Comment by ahmad6242** [comment]
Cant get it through, Whenever i am running the APP using OGX.Mongogx.APP_STORAGE it is throwing me errors.... Can you please with me with this... I am Developing App in Cordova. 

mongogx = new OGX.Mongogx('my_project', 'users', {
            storage: OGX.Mongogx.APP_STORAGE,
            write_concern:{
                mode:OGX.Mongogx.WRITE_DIRECT, //Only supported mode for now, default
                delay:5 //timeout before operation
            }
        });

![image](https://user-images.githubusercontent.com/12858657/38935151-a4f72ce0-432e-11e8-9668-0590d4541318.png)

**Comment by globules-io** [comment]
I see. The APP_STORAGE was never fully tested so I might have to check what's up. Meanwhile, please use the LOCAL_STORAGE to start developing, I will check it out asap.

**Comment by globules-io** [comment]
OK I checked it out and the issue comes from onReadFail, which should create the db files, which loses the scope of "this" in the callback. I will fix ASAP.

**Comment by globules-io** [comment]
Pushed and tested, please update. Let me know if you have any issues.

**Comment by globules-io** [comment]
Forgot to add, wiki updated for Cordova (at bottom)

If you are using APP_STORAGE via Cordova, you must pass and wait for a callback fired when the database is ready, such as

function onDbReady(){

}

 let options = {
      storage:OGX.Mongogx.APP_STORAGE,
      write_concern:{
          mode:OGX.Mongogx.WRITE_DIRECT, //Only supported mode for now, default
          delay:5 //timeout before operation
      },
      callback:onDbReady
 };   

 let mongogx = new OGX.Mongogx(null, null, options);

**Comment by ahmad6242** [comment]
Hello Brother,,, 
Thank you for the Quick Fix.  👍 

A little Problem Still there. 
Now after initializing and the Callback when i try to Insert and Select the Data, it is returning me False... 
Can you please have a look. 

![screenshot_1](https://user-images.githubusercontent.com/12858657/38974627-e7664592-43bb-11e8-8d66-669975b1b6ae.png)
![screenshot_2](https://user-images.githubusercontent.com/12858657/38974628-e78f0be4-43bb-11e8-919b-6996470407eb.png)
![screenshot_3](https://user-images.githubusercontent.com/12858657/38974629-e7b63c78-43bb-11e8-85e1-38e25afda647.png)

**Comment by globules-io** [comment]
Re-select DB & Collection before inserting. Had to skip the ones you pass in the constructor. Will do a fix soon.

**Comment by ahmad6242** [comment]
Thanks MAN... 
That worksss... 
But i will be waiting for the FIX, Hope you will do it soon... 😄 
AGAIN MANY THANKSSS....

**Comment by globules-io** [comment]
Awesome! I will keep this open so I remember to push the fix..

**Comment by ahmad6242** [comment]
OK Thank You... 👍 💗

**Comment by globules-io** [comment]
It should be good now. MongOGX will create _SELECTED_DATABASE_ and _SELECTED_COLLECTION_ if they do not exist, then select. I also added the option to ouput as array or object the result of a find function. Check out the wiki! Please test if you can...

**Comment by ahmad6242** [comment]
OKey i will test it now...

**Comment by ahmad6242** [comment]
Its working Fine........ 😃 👍 
Thanks for the Help...

**Comment by globules-io** [comment]
I will close this issue. Thanks for testing!

**Comment by ahmad6242** [comment]
My Pleasure...
